'use client';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { Bell, Check, CloudUpload, Image as ImageIcon, LogOut, Menu, MessageCircle, Target, Trophy, Zap } from 'lucide-react';
import { supabase } from './lib/supabase-browser';

type Skater={id:string;name:string;active:boolean};
type Trick={trick_id:string;status:string;progress:number;coach_note:string;tricks:{name:string;sort_order:number}|null};
type Note={id:string;body:string;created_at:string};
type Notice={id:string;message:string;created_at:string;is_read:boolean};
const photos=[['/media/3-Photo-3.jpg','Academy session'],['/media/1-Photo-1.jpg','Park crew'],['/media/8-Photo-8.jpg','Finding the line']] as const;
const initials=(name:string)=>name.split(' ').filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'P';
const displayDate=(value:string)=>new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});

export default function Home(){
 const router=useRouter();const[active,setActive]=useState('Progress');const[menuOpen,setMenuOpen]=useState(false);const[parentName,setParentName]=useState('Parent');const[skater,setSkater]=useState<Skater|null>(null);const[tricks,setTricks]=useState<Trick[]>([]);const[notes,setNotes]=useState<Note[]>([]);const[notices,setNotices]=useState<Notice[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{let mounted=true;async function load(){if(!supabase){setError('Supabase is not configured.');setLoading(false);return}const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth/login');return}const[{data:profile},{data:linkedSkater,error:skaterError}]=await Promise.all([supabase.from('profiles').select('parent_name,email').eq('id',user.id).maybeSingle(),supabase.from('skaters').select('id,name,active').eq('parent_user_id',user.id).eq('active',true).order('created_at',{ascending:true}).limit(1).maybeSingle()]);if(!mounted)return;setParentName(String(profile?.parent_name?.trim()||profile?.email?.split('@')[0]||user.email?.split('@')[0]||'Parent'));if(skaterError)setError(skaterError.message);if(!linkedSkater){setLoading(false);return}setSkater(linkedSkater as Skater);const[{data:trickRows},{data:noteRows},{data:noticeRows}]=await Promise.all([supabase.from('skater_tricks').select('trick_id,status,progress,coach_note,tricks(name,sort_order)').eq('skater_id',linkedSkater.id),supabase.from('skater_notes').select('id,body,created_at').eq('skater_id',linkedSkater.id).order('created_at',{ascending:false}).limit(6),supabase.from('notifications').select('id,message,created_at,is_read').eq('skater_id',linkedSkater.id).order('created_at',{ascending:false}).limit(6)]);if(!mounted)return;setTricks(((trickRows||[])as unknown as Trick[]).sort((a,b)=>(a.tricks?.sort_order||0)-(b.tricks?.sort_order||0)));setNotes((noteRows||[])as Note[]);setNotices((noticeRows||[])as Notice[]);setLoading(false)}void load();return()=>{mounted=false}},[router]);
 const completed=tricks.filter(item=>item.status==='mastered'||item.progress>=100).length;const progress=tricks.length?Math.round(tricks.reduce((sum,item)=>sum+item.progress,0)/tricks.length):0;const nextTrick=tricks.find(item=>item.status!=='mastered'&&item.progress<100);const latestNote=notes[0];const coachNote=latestNote?.body||tricks.find(item=>item.coach_note)?.coach_note||'Your coach will add an update after the next session.';const updates=useMemo(()=>notices.length?notices:notes.map(note=>({id:note.id,message:note.body,created_at:note.created_at,is_read:true})),[notices,notes]);const nav=[['Progress',Trophy],['Updates',Bell],['Photos',ImageIcon]]as const;
 function goTo(section:string){setActive(section);document.getElementById(`${section.toLowerCase()}-section`)?.scrollIntoView({behavior:'smooth',block:'start'});setMenuOpen(false)}async function signOut(){await supabase?.auth.signOut();router.replace('/auth/login')}
 if(loading)return <div className="loading-screen"><div className="brand-mark"><Zap size={19} fill="currentColor"/></div><p>Loading your skater&apos;s portal...</p></div>;
 return <main className="app-shell"><aside className={`sidebar ${menuOpen?'open':''}`}><div className="brand"><div className="brand-mark"><Zap size={18} fill="currentColor"/></div><div><strong>MIAMI SKATE</strong><span>ACADEMY</span></div></div><div className="parent-chip"><div className="avatar small">{initials(parentName)}</div><div><span>Parent portal</span><strong>{parentName}</strong></div></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'active':''} onClick={()=>goTo(label)}><Icon size={18}/><span>{label}</span>{label==='Updates'&&updates.length>0&&<i>{updates.length}</i>}</button>)}</nav><div className="sidebar-bottom"><a className="sidebar-link" href="mailto:jt@yointcounty.com?subject=MSA%20parent%20portal"><MessageCircle size={18}/>Contact coach</a><button onClick={signOut}><LogOut size={18}/>Sign out</button></div></aside>
 <section className="content"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMenuOpen(!menuOpen)}><Menu size={20}/></button><div><p className="eyebrow">PARENT PORTAL · {new Date().toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'}).toUpperCase()}</p><h1>{skater?.name||'Skater'}&apos;s skills checklist</h1></div><div className="top-actions"><button className="icon-button" aria-label="View updates" onClick={()=>goTo('Updates')}><Bell size={19}/>{updates.length>0&&<b/>}</button><div className="avatar">{initials(parentName)}</div></div></header><div className="child-switcher"><div className="child-info"><div className="avatar child">{skater?initials(skater.name):'?'}</div><div><span>Current skater</span><strong>{skater?.name||'No skater linked'}</strong></div></div><span className="child-count">{skater?'Active':'Needs setup'}</span></div>
 {!skater&&<section className="empty-state card"><div className="empty-icon"><Trophy size={22}/></div><h2>No skater profile is linked yet</h2><p>{error||'Ask the academy to connect your child to this parent email.'}</p><a className="primary-button" href="mailto:jt@yointcounty.com?subject=Link%20my%20skater%20to%20the%20MSA%20portal">Contact the academy</a></section>}
 <section className="checklist-layout" id="progress-section"><section className="card skills-card"><div className="card-title"><div><span className="muted-label">LIVE SKATER ROADMAP</span><h2>Skills checklist</h2><span>{completed} of {tricks.length} mastered · {progress}% overall</span></div><div className="circle-progress">{completed}<small>/ {tricks.length}</small></div></div><div className="skills-list">{tricks.length?tricks.map(item=><div className="skill-row" key={item.trick_id}><div className={`skill-check ${item.status==='mastered'||item.progress>=100?'done':''}`}>{(item.status==='mastered'||item.progress>=100)&&<Check size={12}/>}</div><div className="skill-copy"><strong>{item.tricks?.name||'Skate skill'}</strong><span>{item.coach_note||(item.progress?'In progress':'Not started')}</span></div><small>{item.progress}%</small></div>):<p className="empty-copy">Skills will appear after your coach sets up the roadmap.</p>}</div></section><aside className="checklist-side"><section className="card progress-card"><span className="muted-label">OVERALL PROGRESS</span><div className="progress-number">{progress}<span>%</span></div><div className="progress-track"><div style={{width:`${progress}%`}}/></div><div className="progress-meta"><span><Trophy size={14}/> {completed} mastered</span><span>{tricks.length} total</span></div></section><section className="card focus-card"><div className="card-title"><div><h3>Coach note</h3><span>{latestNote?`Updated ${displayDate(latestNote.created_at)}`:'Coach updates'}</span></div><Target className="accent-icon" size={21}/></div><div className="focus-main"><div className="focus-icon"><Zap size={20}/></div><div><h4>{nextTrick?.tricks?.name||'Keep practicing'}</h4><p>{coachNote}</p></div></div></section></aside></section>
 <div className="section-title" id="updates-section"><div><span className="muted-label">COACH UPDATES</span><h2>Recent updates</h2></div></div><section className="card sessions-card">{updates.length?updates.slice(0,4).map(item=><div className="session-row" key={item.id}><div className="date-badge"><Bell size={16}/></div><div className="session-info"><h4>{item.message}</h4><span>{displayDate(item.created_at)}</span></div></div>):<p className="empty-copy session-empty">No updates yet. Your coach will add notes here after sessions.</p>}</section>
 <div className="section-title media-heading" id="photos-section"><div><span className="muted-label">ACADEMY MEMORIES</span><h2>Photos</h2></div><a className="upload-button" href="mailto:jt@yointcounty.com?subject=Add%20photos%20to%20the%20MSA%20portal"><CloudUpload size={15}/>Ask coach to add photos</a></div><div className="media-grid">{photos.map(([src,title])=><div className="media-tile" key={title}><div className="media-art"><Image fill sizes="(max-width:700px) 50vw,25vw" src={src} alt={title}/></div><div className="media-caption"><div><strong>{title}</strong><span>Miami Skate Academy</span></div></div></div>)}</div><footer>Miami Skate Academy <span>·</span> Keep rolling.</footer></section></main>
}
