'use client';
import { useState } from 'react';
import { Bell, CalendarDays, Check, ChevronRight, CloudUpload, Image as ImageIcon, LayoutDashboard, LogOut, Menu, MessageCircle, Settings, Sparkles, Target, Trophy, Zap, Play } from 'lucide-react';

const skills = ['Stance & balance','Safe falling','Pushing & stopping','Carving turns','Kick turns'];
const upcoming = ['Drop-ins','Ollie basics'];
const sessions = [
  ['08','SAT','Wynwood Skatepark','Coach Maya'],
  ['05','WED','Miami Beach Ramp','Coach Jordan'],
  ['01','SAT','Wynwood Skatepark','Coach Maya'],
];
export default function Home() {
  const [active,setActive]=useState('Overview'); const [open,setOpen]=useState(false); const [uploaded,setUploaded]=useState(false);
  const nav=[['Overview',LayoutDashboard],['Progress',Trophy],['Sessions',CalendarDays],['Media',ImageIcon],['Goals',Target]] as const;
  const goTo=(section:string)=>{setActive(section); if(section!=='Overview') document.getElementById(section.toLowerCase()+'-section')?.scrollIntoView({behavior:'smooth',block:'start'});};
  return <main className="app-shell">
    <aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brand-mark"><Zap size={18} fill="currentColor"/></div><div><strong>MIAMI SKATE</strong><span>ACADEMY</span></div></div><div className="parent-chip"><div className="avatar small">AM</div><div><span>Parent portal</span><strong>Alex Morgan</strong></div><ChevronRight size={15}/></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'active':''} onClick={()=>{goTo(label);setOpen(false)}}><Icon size={18}/><span>{label}</span>{label==='Media'&&<i>3</i>}</button>)}</nav><div className="sidebar-bottom"><button><MessageCircle size={18}/>Message coach</button><button><Settings size={18}/>Settings</button><button><LogOut size={18}/>Sign out</button></div></aside>
    <section className="content" id="overview-section"><header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setOpen(!open)}><Menu size={20}/></button><div><p className="eyebrow">SATURDAY, AUGUST 8, 2026</p><h1>Good morning, Alex <span>✦</span></h1></div><div className="top-actions"><button className="icon-button"><Bell size={19}/><b/></button><div className="avatar">AM</div></div></header>
      <div className="child-switcher"><div className="child-info"><div className="avatar child">OS</div><div><span>Tracking progress for</span><strong>Olivia Morgan <em>Age 9</em></strong></div></div><button>Switch child <ChevronRight size={15}/></button></div>
      <div className="hero-grid"><section className="welcome-card card"><div className="hero-copy"><div className="tag"><Sparkles size={13}/> THIS WEEK</div><h2>Keep rolling,<br/><span>Olivia!</span></h2><p>Small pushes make big progress. Olivia is building a strong foundation and gaining confidence every session.</p><button className="primary-button" onClick={()=>goTo('Progress')}>View full progress <ChevronRight size={15}/></button></div><div className="hero-art"><img onError={(e)=>{e.currentTarget.style.display="none"}} src="/media/3-Photo-3.jpg" alt="Olivia skating at the park" /><div className="hero-overlay"/></div></section><section className="progress-card card"><div className="section-heading"><div><span className="muted-label">OVERALL PROGRESS</span><h3>Level 2 · Rolling</h3></div><div className="progress-number">68<span>%</span></div></div><div className="progress-track"><div/></div><div className="progress-meta"><span><Trophy size={14}/> 5 skills mastered</span><span>2 to next level</span></div><div className="mini-achievement"><div className="medal"><Trophy size={17}/></div><div><strong>New personal best!</strong><span>5 kick turns in a row</span></div><ChevronRight size={15}/></div></section></div>
      <SectionTitle label="YOUR CHILD" title="Progress snapshot" action="See all progress" onClick={()=>goTo('Progress')}/><div className="snapshot-grid" id="progress-section"><section className="card skills-card"><div className="card-title"><div><h3>Skills tracker</h3><span>5 of 7 skills completed</span></div><div className="circle-progress">5<small>/ 7</small></div></div><div className="skills-list">{skills.map(s=><div className="skill-row" key={s}><div className="skill-check done"><Check size={12}/></div><span>{s}</span></div>)}{upcoming.map(s=><div className="skill-row" key={s}><div className="skill-check"/><span className="up-next">{s}</span><small>UP NEXT</small></div>)}</div></section><section className="card focus-card" id="goals-section"><div className="card-title"><div><h3>Coach note</h3><span>Updated Aug 8 by Coach Maya</span></div><Target className="accent-icon" size={21}/></div><div className="focus-main"><div className="focus-icon"><Zap size={20}/></div><div><h4>Building confidence</h4><p>“Olivia is ready to challenge herself with new ramps. We’re focusing on committing to the drop-in and trusting her balance.”</p></div></div><div className="focus-tags"><span>Drop-ins</span><span>Ramp confidence</span><span>Balance</span></div><button className="outline-button" onClick={()=>goTo('Goals')}>View weekly goals <ChevronRight size={15}/></button></section></div>
      <SectionTitle label="RECENT ACTIVITY" title="Session history" action="View all sessions" onClick={()=>goTo('Sessions')}/><section className="card sessions-card" id="sessions-section">{sessions.map(([day,weekday,location,coach])=><div className="session-row" key={day}><div className="date-badge"><strong>{day}</strong><span>{weekday}</span></div><div className="session-info"><h4>{location}</h4><span>{coach} · August {day}, 2026</span></div><ChevronRight size={17} className="row-arrow"/></div>)}</section>
      <div className="section-title media-heading"><div><span className="muted-label">MEMORIES</span><h2>Latest media</h2></div><label className="upload-button"><CloudUpload size={15}/> {uploaded?'Added!':'Upload'}<input type="file" accept="image/*,video/*" onChange={()=>setUploaded(true)}/></label></div><div className="media-grid" id="media-section"><div className="media-tile"><div className="media-art"><img onError={(e)=>{e.currentTarget.style.display="none"}} src="/media/3-Photo-3.jpg" alt="Kick turn progress"/><div className="play"><Play size={17} fill="white"/></div><span className="duration">0:18</span></div><div className="media-caption"><div><strong>Kick turn progress</strong><span>Aug 8, 2026</span></div><ChevronRight size={15}/></div></div><div className="media-tile"><div className="media-art"><img onError={(e)=>{e.currentTarget.style.display="none"}} src="/media/1-Photo-1.jpg" alt="Saturday session"/></div><div className="media-caption"><div><strong>Saturday session</strong><span>Aug 8, 2026</span></div><ChevronRight size={15}/></div></div><div className="media-tile"><div className="media-art"><img onError={(e)=>{e.currentTarget.style.display="none"}} src="/media/8-Photo-8.jpg" alt="Finding the line"/></div><div className="media-caption"><div><strong>Finding the line</strong><span>Aug 8, 2026</span></div><ChevronRight size={15}/></div></div></div><footer>Miami Skate Academy <span>·</span> Helping young skaters find their flow.</footer>
    </section></main>;
}
function SectionTitle({label,title,action,onClick}:{label:string,title:string,action:string,onClick:()=>void}){return <div className="section-title"><div><span className="muted-label">{label}</span><h2>{title}</h2></div><button className="text-button" onClick={onClick}>{action} <ChevronRight size={14}/></button></div>}




